### ISSUE TITLE
Exception: 'NewStateReason'

### ISSUE THREAD

**Issue by 23ewrdtf** [MrHassanMurtaza/cloudwatch-alarm-to-slack-python#1]
Hi,

I followed your guide and when I sent a test JSON message I get bellow error in Lambda. Would you be able to help?

Runtime: Python 2.7

```
'NewStateReason': Exception
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 58, in lambda_handler
    raise Exception(e)
Exception: 'NewStateReason'
```

**Comment by MrHassanMurtaza** [comment]
Hi,

It means your SNS event body doesn't contain the `NewStateReason` key. Can you post your SNS Alarm event?

Thanks,
Hassan
